// Generates the Fluent 2 design-token layer for the renderer popup.
//
// Reads the official @fluentui/tokens themes and emits CSS custom properties for the
// subset of color tokens the UI consumes, in light / system-dark / explicit-dark
// variants. This is the single source of truth for color — no hand-copied hex.
//
// Output: src/styles/generated/_fluent-tokens.css (inline-imported by renderer.less).
// Run via `npm run generate:tokens` or automatically through the gulp build/watch.
import { createRequire } from "node:module";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const { createDarkTheme, createLightTheme } = require("@fluentui/tokens");
const tokensVersion = require("@fluentui/tokens/package.json").version;

// OneNote brand ramp (Fluent 2 "Colors/Brand/OneNote/*"). Drives every brand/compound
// token below — this is the one palette we deliberately keep instead of a stock brand.
const oneNoteBrandRamp = {
	10: "#100218",
	20: "#210631",
	30: "#310949",
	40: "#410d62",
	50: "#501073",
	60: "#5B1382",
	70: "#6C179A",
	80: "#7719AA",
	90: "#8330B3",
	100: "#9047BD",
	110: "#A05CC8",
	120: "#B277D3",
	130: "#C797E0",
	140: "#DAB8EA",
	150: "#ECDDF5",
	160: "#F9F3FC",
};

// The color tokens the renderer actually uses. Kept intentionally small so the emitted
// CSS stays lean; add a name here when a component needs a new Fluent color.
const colorTokens = [
	"colorNeutralBackground1",
	"colorNeutralBackground2",
	"colorNeutralBackground3",
	"colorNeutralForeground1",
	"colorNeutralForeground2",
	"colorNeutralForeground3",
	"colorNeutralForeground4",
	"colorNeutralForegroundOnBrand",
	"colorNeutralStroke1",
	"colorNeutralStroke2",
	"colorNeutralStroke3",
	"colorSubtleBackgroundHover",
	"colorSubtleBackgroundPressed",
	"colorCompoundBrandBackground",
	"colorCompoundBrandBackgroundHover",
	"colorCompoundBrandBackgroundPressed",
	"colorStatusSuccessForeground1",
	"colorStatusDangerForeground1",
	"colorStatusDangerBackground1",
];

const lightTheme = createLightTheme(oneNoteBrandRamp);
const darkTheme = createDarkTheme(oneNoteBrandRamp);

const declarations = (theme, colorScheme) => {
	const lines = colorTokens.map((name) => {
		const value = theme[name];
		if (value === undefined) {
			throw new Error(`@fluentui/tokens is missing color token "${name}"`);
		}
		return `\t--${name}: ${value};`;
	});
	lines.push(`\tcolor-scheme: ${colorScheme};`);
	return lines.join("\n");
};

const banner =
	`/* AUTO-GENERATED by tools/generateFluentTokens.mjs from @fluentui/tokens@${tokensVersion}.\n` +
	" * Do not edit by hand — run `npm run generate:tokens`.\n" +
	" * Source of truth for Fluent 2 color tokens (OneNote brand ramp). */";

const css = `${banner}

:root,
:root[data-theme="light"] {
${declarations(lightTheme, "light")}
}

/* System preference drives dark when the user hasn't explicitly chosen a theme. */
@media (prefers-color-scheme: dark) {
	:root:not([data-theme]),
	:root[data-theme="system"] {
${declarations(darkTheme, "dark")}
	}
}

/* Explicit user override via the in-app theme toggle. */
:root[data-theme="dark"] {
${declarations(darkTheme, "dark")}
}
`;

const outDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "src", "styles", "generated");
const outFile = path.join(outDir, "_fluent-tokens.css");
await mkdir(outDir, { recursive: true });
await writeFile(outFile, css, "utf8");
console.log(`Generated ${path.relative(process.cwd(), outFile)} from @fluentui/tokens@${tokensVersion}`);
